services:
    meeting:
        class: BBBLoadBalancer\AdminBundle\Service\MeetingService
        arguments: [ @doctrine_mongodb, @validator ]
    bbb:
        class: BBBLoadBalancer\AdminBundle\Service\BBBService
        arguments: [ %bbb.salt% ]
    server:
        class: BBBLoadBalancer\AdminBundle\Service\ServerService
        arguments: [ @doctrine_mongodb, @bbb, @validator ]